os:
  - linux
  - osx
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 4.1
  - 4.5
  - 5.0
  - 5.5
  - 5.12
  - 6
  - 6.6
  - node
  - lts/argon
  - lts/*
  - iojs
install: npm install
before_script:
  - "npm install -g grunt-cli"
  - "grunt build"
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
