# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"

pull_requests:
  do_not_increment_build_number: true

platform: Any CPU
shallow_clone: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff. Use msvs 2013 for the hiredis parser
  - npm install
  - npm install -g grunt-cli mocha
  - grunt build

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - cmd: grunt test

os:
  - Default Azure
  - Windows Server 2012 R2

# Don't actually build using MSBuild
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
